### ISSUE TITLE
Chat bot errors and stops when using certain characters

### ISSUE THREAD

**Issue by ASOwnerYT** [Rahuletto/simply-djs#10]
**Describe the bug**
When you use characters that aren't in the English alplabet, like ç for example, the bot crashes with the following error:

```
`C:\Users\asown\Documents\GitHub\ASOwnerYT-Pet-Discord-Bot\node_modules\node-fetch\lib\index.js:272
                                return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
                                                           ^
FetchError: invalid json response body at https://api.affiliateplus.xyz/api/chatbot?message=ç&botname=ASOwnerYT%27s%20Pet&ownername=Rahuletto#0243&user=402581422176600064 reason: Unexpected end of JSON input
    at C:\Users\asown\Documents\GitHub\ASOwnerYT-Pet-Discord-Bot\node_modules\node-fetch\lib\index.js:272:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'invalid-json'
}
```

**To Reproduce**
1. Start the bot
2. Type invalid characters in the chatbot channel
3. The bot will crash with the error above

**Expected behavior**
The bot should just print the error to the console and keep running. `Try` and `catch` doesn't prevent the bot from crashing.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: Latest

**Comment by Rahuletto** [comment]
Ok we will try to fix the bug as soon as possible

**Comment by Rahuletto** [comment]
Fixed the bug 🙂
