### ISSUE TITLE
Error upon starting the bot

### ISSUE THREAD

**Issue by WolvedDevving** [Rahuletto/simply-djs#26]
**Describe the bug**
Pretty much when i try starting the bot I get this error: SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47

**To Reproduce**
1. Run the bot
2. Try the function
3. See error

**Expected behavior**
The bot starting ig lol

**Screenshots**
https://gyazo.com/cc483cecccff90c6b5d63584e7b1a509

**Versions (please complete the following information):**
 - Discord.js Version v13
 - simply-djs Version latest 

**Additional context**
I'm dumb

**Comment by Xx-Mohit-xX** [comment]
Bruh this is not a bot source code its a package, read docs to know how to use it@WolvedDevving

**Comment by Rahuletto** [comment]
1. This is occured from node fetch
2. Somewhere from ur code

**Comment by Rahuletto** [comment]
> Bruh this is not a bot source code its a package, read docs to know how to use it@WolvedDevving

Can I close this issue then ?

**Comment by A-K-O-R-A** [comment]
What version of `node-fetch` are you using, it should be smth like 2.x.x and you should create this issue at the node-fetch repository because this is not related to this package.

**Comment by WolvedDevving** [comment]
I'm using node fetch v2.6.5. And I've read the docs this is an issue on my end probably but I've installed everything needed so I haven't got a clue why this isn't working resulting in me opening this bug report.

**Comment by Xx-Mohit-xX** [comment]
> I'm using node fetch v2.6.5. And I've read the docs this is an issue on my end probably but I've installed everything needed so I haven't got a clue why this isn't working resulting in me opening this bug report.

This isn't a bot source code, so we can't help you to fix bugs occured from running the package as a bot

**Comment by WolvedDevving** [comment]
Thennn why make a bug repo in the first place??

**Comment by A-K-O-R-A** [comment]
@Rahuletto Pls close this issue

**Comment by Rahuletto** [comment]
> Thennn why make a bug repo in the first place??

If u see, this is a package repo.. not ur bot src code bug repo.. 😂
