### ISSUE TITLE
Security Vulnerabilities - Outdated NPM Packages

### ISSUE THREAD

**Issue by WolfTM** [Rahuletto/simply-djs#49]
You currently use:

`	"dependencies": {
		"ms": "^2.1.3",
		"node-fetch": "2.6.1",
		"quickmongo": "^3.0.0"
	},`
	
These contain security vulnerabilities!!

Please change them to the latest versions as shown in example below.

`	"dependencies": {
		"ms": "^2.1.3",
		"node-fetch": "3.1.0",
		"quickmongo": "^4.0.0"
	},`
	
Please always keep your node packages up to date!

Hope you can bring out an update with the updated npm packages

**Comment by Rahuletto** [comment]
But as you see nodefetch latest is a ES module and quickmongo v4 is very different than v3. So we cannot update the packages. We are very sorry 🙏

**Comment by Rahuletto** [comment]
We found many alternatives to fix these security vulnerabilities.. We planned to use axios and mongoose..

**Comment by Zaid-maker** [comment]
@Rahuletto use depfu or dependabot to automate your dependencies
