### ISSUE TITLE
Suggestion System - Reaction Bug

### ISSUE THREAD

**Issue by LHCLYT** [Rahuletto/simply-djs#53]
**Describe the bug**
With the suggestion system, if you have 2 active suggestions, and you reject one of them, the next one you reject will have the same reason.

**To Reproduce**
To reproduce it just use the suggestion system, make 2 suggestions, and try to accept both, both will have the same reason.

**Expected behavior**
That each suggestion has a reason separate from the others.

**Versions (please complete the following information):**
 - Discord.js Version: 13.6
 - simply-djs Version: latest

**Comment by Rahuletto** [comment]
Thank u for the report. We managed to reproduce the problem. Trying to fix the bug 🐞

**Comment by LHCLYT** [comment]
Have you found the problem?

**Comment by Rahuletto** [comment]
It is not a problem.. We wanted to make the admin reaction panel ephemeral (hidden for everyone) and u can't have collector for that message. you can only do it by having collector in channel. 

We still don't know how to fix this. if we try to fix it. We can't achieve the ephemeral message.

**Comment by Rahuletto** [comment]
Try v3 ;)
