### ISSUE TITLE
Ticket System Crash

### ISSUE THREAD

**Issue by loulou133** [Rahuletto/simply-djs#65]
**Describe the bug**

When I create the ticket from the 🎫 Ticket button, it works but when I click on it again, it crashes the bot without telling me that I already created a ticket
![image](https://user-images.githubusercontent.com/72643424/162587115-de3a15c5-be91-4866-8a6c-e0dac697ef73.png)

**Versions (please complete the following information):**
 - Discord.js Version v13
 - simply-djs Version ^2.5.2

**Comment by Rahuletto** [comment]
Try v3.0.0-dev-1 ;)
