### ISSUE TITLE
rankCard bugging - Poppins Semi-Bold Not-Rotated

### ISSUE THREAD

**Issue by rodycouto** [Rahuletto/simply-djs#66]
Yesterday (08/05/2022) my bot explode an error in the rankCard.

This is the error
![image](https://user-images.githubusercontent.com/70030588/167525813-d9c3348d-cbc4-40a7-bca2-9175b84ee921.png)

This is the function that send the image from rankCard
```js
async function SendLevel() {
    const msg = await message.reply(`${e.Loading} | Carregando...`) // Loading message

    let reData = await Database.User.findOne({ id: user.id }, 'Walls.Set') // Get the URL IMAGE from database

    try {
        Database.updateUserData(message.author.id, 'Timeouts.LevelImage', Date.now()) // Setting a timeout to block spams

        await simplydjs.rankCard(client, message, {
            member: user, // String
            level: level || 0, // Number
            currentXP: exp || 0, // Number
            neededXP: xpNeeded || 0, // Number
            rank: rank || 0, // Number,
            slash: false // It isn't a slash command
            background: reData.Walls?.Set || LevelWallpapers?.bg0?.Image || null // Image URL from Discord Chats || It's work perfectly
        }).then(() => {
            msg.delete().catch(() => { }) // Delete the loading message
        }).catch(err => { ErrorHandler(err) })

        return

    } catch (err) { return Error(message, err) }
}
```
This is the amazing rankCard with a custom background
![image](https://user-images.githubusercontent.com/70030588/167526198-1cdd76af-ad6f-457a-9589-b107ecfe5a6c.png)

The bug make this...
![image](https://user-images.githubusercontent.com/70030588/167526318-18aef2b3-a638-4523-ac73-dd89b5fdd9c6.png)

**Comment by Rahuletto** [comment]
We are sorry that this function is already deprecated and also removed in the latest version. You can try simply-xp package to use the rankCard system

**Comment by rodycouto** [comment]
> We are sorry that this function is already deprecated and also removed in the latest version. You can try simply-xp package to use the rankCard system

OMG! That a old version from simply-xp can i use? I really love this lib

**Comment by Rahuletto** [comment]
> > We are sorry that this function is already deprecated and also removed in the latest version. You can try simply-xp package to use the rankCard system
> 
> OMG! That a old version from simply-xp can i use? I really love this lib

Yea it's your rights to use any version ♥️

**Comment by rodycouto** [comment]
> > > We are sorry that this function is already deprecated and also removed in the latest version. You can try simply-xp package to use the rankCard system
> > 
> > 
> > OMG! That a old version from simply-xp can i use? I really love this lib
> 
> Yea it's your rights to use any version ♥️

Please! Can you an old version that rankCard works perfectly?

**Comment by rodycouto** [comment]
If someone get the same problem, don't worry!
Just use this `-npm install simply-djs@2.0.99`
