### ISSUE TITLE
Nevermind.

### ISSUE THREAD

**Issue by AudiRo2993** [Rahuletto/simply-djs#98]
Nevermind, i've found solutions

**Comment by Rahuletto** [comment]
If u are modifying the code, you cannot distribute (publish) it as per the license `CC BY-NC-ND 4.0` Learn more about the license here https://creativecommons.org/licenses/by-nc-nd/4.0/.

You are allowed to modify and using it for personal use (not publishing). 

This doesn't need an issue as you can contact me directly in discord. And yea errors in ur git clone doesn't mean this project has issues so yea.
